### ISSUE TITLE
Request / Response created two `reply_to` queues

### ISSUE THREAD

**Issue by rtorino** [derickbailey/rabbus#1] opened 2014-12-25 07:23 UTC
Hi Derick,

I tried request / request (RPC) object pair and noticed that the requester creates a temporary `reply_to` queue and when I started the responder, it also creates another temporary queue, but only the first was used. Can you explain why?

![screen shot 2014-12-25 at 15 21 49](https://cloud.githubusercontent.com/assets/1680608/5552845/dd945946-8c49-11e4-9435-ff28b759347a.png)

**Comment by mxriverlynn** [comment] 2014-12-25 12:11
d'oh! i had not noticed that before... but in checking my request response demo in the demo folder of the repo, it is doing that. i'll have to dig in and see if i can figure this out.

**Comment by mxriverlynn** [comment] 2014-12-25 12:21
it looks like this may be a problem in Wascally... i think it is creating a response queue for every connection i make, even if i don't create or bind a queue in that connection. i'll open an issue with them and see if we can get that corrected

**Comment by rtorino** [comment] 2014-12-25 12:51
I agree that this could be a problem with Wascally. Thanks!

**Comment by mxriverlynn** [comment] 2015-02-26 15:51
this is by design in wascally - see referenced wascally ticket. they may change this ability in the future. but for now i'm going to close this.

**Closed as completed by mxriverlynn** 2015-02-26 15:51 UTC

**Comment by infiniteluke** [comment] 2015-08-31 19:29
By adding 

``` javascript
{
  'replyQueue': false
}
```

to your config passed into wascally.configure(), you should be able to stop theses from being created. https://github.com/arobson/wascally/commit/490e6801a8726ea59015a55655404ba92d12d424

I can confirm this works on the Sender object. No more extraneous reply-to queues!
